project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tree.urls', namespace = 'tree')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


tree/urls.py
from django.urls import path
from . import views
from . import api

app_name = 'tree'


urlpatterns = [
    path('', views.index , name = 'index'),
    path('naeem', views.naeem , name = 'naeem'),
    path('log', views.log_history , name = 'log'),

    path('branch-create', api.CreateBranch.as_view(), name = 'branch-create'),
    path('branch-update/<int:pk>', api.BranchUpdate.as_view(), name = 'branch-update'),

    path('naeem/branch-create', api.CreateFamilyBranch.as_view(), name = 'family-branch-create'),
    path('naeem/branch-update/<int:pk>', api.FamilyBranchUpdate.as_view(), name = 'family-branch-update'),
]

tree/models.py
from django.db import models
from django.utils import timezone


class Person(models.Model):
    name = models.CharField(max_length= 50, blank=False, null=False)
    fname  = models.TextField(null = True, blank = True)
    url   = models.URLField(default="", null = True, blank = True)

    parent = models.ForeignKey('self', on_delete=models.CASCADE, null = True, blank = True)
    rank   = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.get_fname

    def save(self, *args, **kwargs):
        if self.parent:
            self.rank = self.parent.rank + 1 # determine rank of child
        super().save(*args, **kwargs)

    @property
    def get_fname(self):
        name = self.name
        if self.parent:
            name += '-' + self.parent.get_fname
        return name



class Family(models.Model):
    name = models.CharField(max_length= 20, blank=False, null=False)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null = True, blank = True)
    rank   = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.get_fname

    def save(self, *args, **kwargs):
        if self.parent:
            self.rank = self.parent.rank + 1 # determine rank of child
        super().save(*args, **kwargs)

    @property
    def get_fname(self):
        name = self.name
        if self.parent:
            name += ' ' + self.parent.get_fname
        return name



def summer_time():
    return timezone.now() + timezone.timedelta(hours=1)

class Hist(models.Model):
    date = models.DateTimeField(default=summer_time)

class Log_Info(models.Model):
    ip               = models.CharField(max_length= 200, blank=True, null=True)
    device_type      = models.CharField(max_length= 200, blank=True, null=True)
    browser_type     = models.CharField(max_length= 200, blank=True, null=True)
    browser_version  = models.CharField(max_length= 200, blank=True, null=True)
    os_type          = models.CharField(max_length= 200, blank=True, null=True)
    os_version       = models.CharField(max_length= 200, blank=True, null=True)
    location_country = models.CharField(max_length= 200, blank=True, null=True)
    location_city    = models.CharField(max_length= 200, blank=True, null=True)
    history          = models.ManyToManyField(Hist, blank = True)

    def __str__(self):
        return self.ip

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError





def validate_name(name):
    if not(name) or name.isspace():
        raise ValidationError('empty name is not valid name')  




class MyUser(AbstractUser):
    email         = models.EmailField(unique=True, blank=False, null=False)
    phone_regex   = RegexValidator(regex="[0][1][0125][0-9][ ]?\d{3}[ ]?\d{4}", message="Phone number must be entered in the format: '01xx xxx xxxx'. Up to 11 digits allowed.")
    phone         = models.CharField(validators=[phone_regex], max_length=11, blank=False, null=False) # validators should be a list
    first_name    = models.CharField(validators=[validate_name], max_length=30, blank=False, null=False)
    last_name     = models.CharField(validators=[validate_name], max_length=30, blank=False, null=False)
    
    REQUIRED_FIELDS = ['email', 'first_name']
    

    def __str__(self):
        return self.email

    
    @property
    def get_name(self):
        name = self.first_name
        if self.last_name:
            name += ' ' + self.last_name
        return name
        
    

tree/views.py
from django.shortcuts import render
from .models import Person, Family, Hist, Log_Info
from django.contrib.gis.geoip2 import GeoIP2
from django.contrib.auth.decorators import user_passes_test



def get_info(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')

    device_type = ""
    browser_type = ""
    browser_version = ""
    os_type = ""
    os_version = ""
    if request.user_agent.is_mobile:
        device_type = "Mobile"
    if request.user_agent.is_tablet:
        device_type = "Tablet"
    if request.user_agent.is_pc:
        device_type = "PC"

    browser_type = request.user_agent.browser.family
    browser_version = request.user_agent.browser.version_string
    os_type = request.user_agent.os.family
    os_version = request.user_agent.os.version_string


    g = GeoIP2()
    location = g.city(ip)

    location_country = location["country_name"]
    location_city = location["city"]

    context = {
        "ip": ip,
        "device_type": device_type,
        "browser_type": browser_type,
        "browser_version": browser_version,
        "os_type":os_type,
        "os_version":os_version,
        "location_country": location_country,
        "location_city": location_city
    }
    date = Hist.objects.create()
    log, created = Log_Info.objects.get_or_create(**context)
    log.history.add(date)
    return context


def index(request):
    try:
        get_info(request)
    except:
        pass
    qs = Person.objects.all()
    if qs:
        ctx = {'root' : qs[0]}
    else:
        ctx = {'root' : ''}
    if request.user.is_authenticated and request.user.is_superuser:
        return render(request, 'edit-tree.html', context=ctx)
    return render(request, 'index.html', context=ctx)



def naeem(request):
    try:
        get_info(request)
    except:
        pass
    qs = Family.objects.all()
    if qs:
        ctx = {'root' : qs[0]}
    else:
        ctx = {'root' : ''}
    if request.user.is_authenticated and request.user.is_superuser:
        return render(request, 'naeem-edit.html', context=ctx)
    return render(request, 'naeem.html', context=ctx)


def is_admin(user):
    return user.is_authenticated and user.is_superuser and user.username == "admin"



@user_passes_test(is_admin, login_url='/admin' )
def log_history(request):
    ctx = dict()
    try:
        info = get_info(request)
    except:
        info = dict()
    qs = Log_Info.objects.all()
    ctx['logs'] = qs
    ctx.update(info)
    return render(request, 'log.html', ctx)

user/views.py
from django.shortcuts import render

# Create your views here.

templates/edit-tree.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Tree</title>

<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
</head>
<body>

<style>

/*----------------genealogy-scroll----------*/

.genealogy-scroll::-webkit-scrollbar {
    width: 5px;
    height: 8px;
}
.genealogy-scroll::-webkit-scrollbar-track {
    border-radius: 10px;
    background-color: #e4e4e4;
}
.genealogy-scroll::-webkit-scrollbar-thumb {
    background: #212121;
    border-radius: 10px;
    transition: 0.5s;
}
.genealogy-scroll::-webkit-scrollbar-thumb:hover {
    background: #d5b14c;
    transition: 0.5s;
}


/*----------------genealogy-tree----------*/
.genealogy-body{
    white-space: nowrap;
    overflow-y: hidden;
    padding: 50px;
    min-height: 500px;
    padding-top: 200px;
    text-align: center;
}
.genealogy-tree{
  display: inline-block;
}
.genealogy-tree ul {
    padding-top: 20px;
    position: relative;
    padding-left: 0px;
    display: flex;
    justify-content: center;
}
.genealogy-tree li {
    float: left; text-align: center;
    list-style-type: none;
    position: relative;
    padding: 20px 5px 0 5px;
}
.genealogy-tree li::before, .genealogy-tree li::after{
    content: '';
    position: absolute;
    top: 0;
    right: 50%;
    border-top: 2px solid #ccc;
    width: 50%;
  height: 18px;
}
.genealogy-tree li::after{
    right: auto; left: 50%;
    border-left: 2px solid #ccc;
}
.genealogy-tree li:only-child::after, .genealogy-tree li:only-child::before {
    display: none;
}
.genealogy-tree li:only-child{
    padding-top: 0;
}
.genealogy-tree li:first-child::before, .genealogy-tree li:last-child::after{
    border: 0 none;
}
.genealogy-tree li:last-child::before{
    border-right: 2px solid #ccc;
    border-radius: 0 5px 0 0;
    -webkit-border-radius: 0 5px 0 0;
    -moz-border-radius: 0 5px 0 0;
}
.genealogy-tree li:first-child::after{
    border-radius: 5px 0 0 0;
    -webkit-border-radius: 5px 0 0 0;
    -moz-border-radius: 5px 0 0 0;
}
.genealogy-tree ul ul::before{
    content: '';
    position: absolute; top: 0; left: 50%;
    border-left: 2px solid #ccc;
    width: 0; height: 20px;
}
.genealogy-tree li a{
    text-decoration: none;
    color: #666;
    font-family: arial, verdana, tahoma;
    font-size: 11px;
    display: inline-block;
    border-radius: 5px;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
}

.genealogy-tree li a:hover+ul li::after,
.genealogy-tree li a:hover+ul li::before,
.genealogy-tree li a:hover+ul::before,
.genealogy-tree li a:hover+ul ul::before{
    border-color:  #fbba00;
}

/*--------------memeber-card-design----------*/
.member-view-box{
    padding:0px 20px;
    text-align: center;
    border-radius: 4px;
    position: relative;
}
.member-image{
    width: 60px;
    position: relative;
}
.member-image img{
    width: 60px;
    height: 60px;
    border-radius: 6px;
  background-color :#000;
  z-index: 2;
}


 header {
    background: #fff;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    z-index: 1;
    box-shadow: 0px 0px 6px 0px rgba(0, 0, 0, 0.5);
 }


 * {
    box-sizing: border-box;
  }
 .columnform {
    float: left;
    width: 50%;
    padding: 10px;
  }


 input[type=text] {
    width: 100%;
    padding: 4px 20px;
    margin: 4px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  input[type=button] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 5px 20px;
    margin: 4px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  input[type=button]:hover {
    background-color: #45a049;
  }

  .editbox {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
  }


</style>

<header >
    <div>
        <div class="columnform editbox">
            <form>
                <input type="text" id="name-update" name="name" placeholder="name..">
                <input type="text" id="fname-update" name="fname" placeholder="full name..">
                <input type="text" id="url-update" name="url" placeholder="url..">
                <input type="hidden" id="pk-update" name="pk-update">
                <input type="button" value="update data" onclick="update_branch(this)">
          </form>
        </div>
        <div class="columnform editbox">
            <form>
                <input type="text" id="name-add" name="name" placeholder="name..">
                <input type="text" id="fname-add" name="fname" placeholder="full name..">
                <input type="text" id="url-add" name="url" placeholder="url..">
                <input type="hidden" id="parent-pk" name="parent-pk">
                <input type="button" value="add branch" onclick="create_branch(this)">
          </form>
        </div>
    </div>
</header>

<!--draw tree test 2-->
<div class="body genealogy-body genealogy-scroll">
    <div class="genealogy-tree">
        <ul>
            <li id="li-{{root.pk}}">
                <a href="javascript:void(0);" onclick="show_data(this)" id="{{root.pk}}">
                    <div class="member-view-box">
                        <div class="member-details">
                            <h3 id="branch-name-{{root.pk}}">{{root.name}}({{root.rank}})</h3>
                            <input type="hidden" id="name-{{root.pk}}" name="name" value="{{root.name}}">
                            <input type="hidden" id="fname-{{root.pk}}" name="fname" value="{{root.fname}}">
                            <input type="hidden" id="url-{{root.pk}}" name="url" value="{{root.url}}">
                        </div>

                    </div>
                </a>

                {% if root.person_set.all %}
                    <ul id="branch-id-{{root.pk}}">
                    {%for node in root.person_set.all %}
                        {%include "tree.html" %}
                    {%endfor%}
                    </ul>
                {% endif %}
            </li>
        </ul>
    </div>
</div>


<script>
    {% comment %} $(function () {
        $('.genealogy-tree ul').hide();
        $('.genealogy-tree>ul').show();
        $('.genealogy-tree ul.active').show();
        $('.genealogy-tree li').on('click', function (e) {
            var children = $(this).find('> ul');
            if (children.is(":visible")) children.hide('fast').removeClass('active');
            else children.show('fast').addClass('active');
            e.stopPropagation();
        });
    }); {% endcomment %}

    function show_data(element)
    {
        pk = element.id;
        let name = document.getElementById('name-'+ pk).value;
        let fname = document.getElementById('fname-'+ pk).value;
        let url = document.getElementById('url-'+ pk).value;

        document.getElementById("name-update").value = name;
        document.getElementById("fname-update").value = fname;
        document.getElementById("url-update").value = url;
        document.getElementById("pk-update").value = pk;
        document.getElementById("parent-pk").value = pk;

    }


    function update_branch(element)
    {
        let data = {};
        data['name']  = document.getElementById("name-update").value;
        data['fname']  = document.getElementById("fname-update").value;
        data['url']  = document.getElementById("url-update").value;
        let pk =document.getElementById("pk-update").value;

        let xhttp = new XMLHttpRequest();
        xhttp.open("PUT", "/branch-update/"+pk, true);
        const csrftoken = getCookie('csrftoken');
        xhttp.setRequestHeader('x-csrftoken', csrftoken)
        xhttp.setRequestHeader('Content-Type', 'application/json; charset=UTF-8')
        xhttp.setRequestHeader('Accept', 'application/json')

        xhttp.onreadystatechange = function()
        {
          if (this.readyState == 4 && this.status == 200)
          {
            response = JSON.parse(this.responseText)

            document.getElementById("branch-name-"+pk).innerHTML = response.name;
            document.getElementById("name-"+pk).value = response.name;
            document.getElementById("fname-"+pk).value = response.fname;
            document.getElementById("url-"+pk).value = response.url;
          }
        }

        xhttp.send(JSON.stringify(data));
    }




    function draw_branch(response, parent){
        let htmltext =  '<li id="li-'+response.id+'>'+
                '    <a href="javascript:void(0);" onclick="show_data(this)" id="'+response.id+'">'+
                '        <div class="member-view-box">'+
                '                <div class="member-details">'+
                '                    <h3 id="branch-name-'+response.id+'">'+response.name+'('+parent+')'+'</h3>'+
                '                    <input type="hidden" id="name-'+response.id+'" name="name" value="'+response.name+'">'+
                '                    <input type="hidden" id="fname-'+response.id+'" name="fname" value="'+response.fname+'">'+
                '                    <input type="hidden" id="url-'+response.id+'" name="url" value="'+response.url+'">'+
                '                </div>'+
                '        </div>'+
                '    </a>'+
                '</li>'

        return htmltext;
    }


    function create_branch(element)
    {
        let data = {};
        data['name']  = document.getElementById("name-add").value;
        data['fname']  = document.getElementById("fname-add").value;
        data['url']  = document.getElementById("url-add").value;
        data['parent']  = document.getElementById("parent-pk").value;


        let xhttp = new XMLHttpRequest();
        xhttp.open("POST", "/branch-create", true);
        const csrftoken = getCookie('csrftoken');
        xhttp.setRequestHeader('x-csrftoken', csrftoken)
        xhttp.setRequestHeader('Content-Type', 'application/json; charset=UTF-8')
        xhttp.setRequestHeader('Accept', 'application/json')

        xhttp.onreadystatechange = function()
        {
          if (this.readyState == 4 && this.status == 201)
          {
            response = JSON.parse(this.responseText)

            parent = document.getElementById("parent-pk").value;
            new_branch = draw_branch(response, parent);

            if (document.getElementById('branch-id-'+ pk)){
                document.getElementById('branch-id-'+ pk).innerHTML += new_branch;
            } else {
                document.getElementById("li-"+pk).innerHTML += '<ul id="branch-id-'+parent+
                                                    '>'+
                                                        new_branch +
                                                        '</ul>';
            }


          }
        }

        xhttp.send(JSON.stringify(data));

    }

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }


</script>


</body>
</html>

templates/family.html
<li id="li-{{node.pk}}">
    <a href="javascript:void(0);" onclick="show_data(this)" id="{{node.pk}}">
        <div class="member-view-box">
                <div class="member-details">
                    <h1 style="font-size: 200%" id="branch-name-{{node.pk}}">{{node.name}}</h1>
                    <input type="hidden" id="name-{{node.pk}}" name="name" value="{{node.get_fname}}">
                </div>
        </div>
    </a>
    {% if node.family_set.all %}
        <ul id="branch-id-{{node.pk}}">
        {%for ch in node.family_set.all %}
            {%with node=ch template_name="family.html" %}
                {%include template_name%}
            {%endwith%}
        {%endfor%}
        </ul>
    {% endif %}
</li>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" content="width=device-width, initial-scale=1.0">
<title>Tree</title>

<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
</head>
<body>

<style>

/*----------------genealogy-scroll----------*/

.genealogy-scroll::-webkit-scrollbar {
    width: 5px;
    height: 8px;
}
.genealogy-scroll::-webkit-scrollbar-track {
    border-radius: 10px;
    background-color: #e4e4e4;
}
.genealogy-scroll::-webkit-scrollbar-thumb {
    background: #212121;
    border-radius: 10px;
    transition: 0.5s;
}
.genealogy-scroll::-webkit-scrollbar-thumb:hover {
    background: #d5b14c;
    transition: 0.5s;
}


/*----------------genealogy-tree----------*/
.genealogy-body{
    white-space: nowrap;
    overflow-y: hidden;
    padding: 50px;
    min-height: 500px;
    padding-top: 150px;
    text-align: center;
}
.genealogy-tree{
  display: inline-block;
}
.genealogy-tree ul {
    padding-top: 20px;
    position: relative;
    padding-left: 0px;
    display: flex;
    justify-content: center;
}
.genealogy-tree li {
    float: left; text-align: center;
    list-style-type: none;
    position: relative;
    padding: 20px 5px 0 5px;
}
.genealogy-tree li::before, .genealogy-tree li::after{
    content: '';
    position: absolute;
    top: 0;
    right: 50%;
    border-top: 2px solid #ccc;
    width: 50%;
  height: 18px;
}
.genealogy-tree li::after{
    right: auto; left: 50%;
    border-left: 2px solid #ccc;
}
.genealogy-tree li:only-child::after, .genealogy-tree li:only-child::before {
    display: none;
}
.genealogy-tree li:only-child{
    padding-top: 0;
}
.genealogy-tree li:first-child::before, .genealogy-tree li:last-child::after{
    border: 0 none;
}
.genealogy-tree li:last-child::before{
    border-right: 2px solid #ccc;
    border-radius: 0 5px 0 0;
    -webkit-border-radius: 0 5px 0 0;
    -moz-border-radius: 0 5px 0 0;
}
.genealogy-tree li:first-child::after{
    border-radius: 5px 0 0 0;
    -webkit-border-radius: 5px 0 0 0;
    -moz-border-radius: 5px 0 0 0;
}
.genealogy-tree ul ul::before{
    content: '';
    position: absolute; top: 0; left: 50%;
    border-left: 2px solid #ccc;
    width: 0; height: 20px;
}
.genealogy-tree li a{
    text-decoration: none;
    color: #666;
    font-family: arial, verdana, tahoma;
    font-size: 11px;
    display: inline-block;
    border-radius: 5px;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
}

.genealogy-tree li a:hover+ul li::after,
.genealogy-tree li a:hover+ul li::before,
.genealogy-tree li a:hover+ul::before,
.genealogy-tree li a:hover+ul ul::before{
    border-color:  #fbba00;
}

/*--------------memeber-card-design----------*/
.member-view-box{
    padding:0px 20px;
    text-align: center;
    border-radius: 4px;
    position: relative;
}
.member-image{
    width: 60px;
    position: relative;
}
.member-image img{
    width: 60px;
    height: 60px;
    border-radius: 6px;
  background-color :#000;
  z-index: 2;
}


 header {
    background: #fff;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    z-index: 1;
    box-shadow: 0px 0px 6px 0px rgba(0, 0, 0, 0.5);
 }



</style>

<header  dir="rtl" >

    <h2><span style="font-size: 100%; padding:10px;"> اللقب :</span> <span id="name-show" style="font-size: 80%;"> </span> <h2>
    <h2><span style="font-size: 100%; padding:10px;"> الاسم : </span> <span id="fname-show" style="font-size: 80%;"> </span></h2>
    <h2><span style="font-size: 100%; padding:10px;"> المصدر : </span> <a id="url-show" href="#" style="font-size: 80%;"> </a></h2>

</header>


<div class="body genealogy-body genealogy-scroll">
    <div class="genealogy-tree">
        <ul>
            <li>
                <a href="javascript:void(0);" onclick="show_data(this)" id="{{root.pk}}">
                    <div class="member-view-box">
                            <div class="member-details">
                                <h1 style="font-size: 400%"> اضغط على الاسم </h1>
                                <p></p>
                                <h1 style="font-size: 200%" >{{root.name}}</h1>
                                <input type="hidden" id="name-{{root.pk}}" name="name" value="{{root.name}}">
                                <input type="hidden" id="fname-{{root.pk}}" name="fname" value="{{root.fname}}">
                                <input type="hidden" id="url-{{root.pk}}" name="url" value="{{root.url}}">
                            </div>
                    </div>
                </a>
                <ul>
                {%for node in root.person_set.all %}
                    {%include "tree.html" %}
                {%endfor%}
                </ul>

            </li>
        </ul>
    </div>
</div>


<script>
    $(function () {
        $('.genealogy-tree ul').hide();
        $('.genealogy-tree>ul').show();
        $('.genealogy-tree ul.active').show();
        $('.genealogy-tree li').on('click', function (e) {
            var children = $(this).find('> ul');
            if (children.is(":visible")) children.hide('fast').removeClass('active');
            else children.show('fast').addClass('active');
            e.stopPropagation();
        });
    });


    function show_data(element)
    {
        pk = element.id;
        let name = document.getElementById('name-'+ pk).value;
        let fname = document.getElementById('fname-'+ pk).value;
        let url = document.getElementById('url-'+ pk).value;

        document.getElementById("name-show").innerHTML = name;
        document.getElementById("fname-show").innerHTML = fname;
        document.getElementById("url-show").innerHTML = url;
        document.getElementById("url-show").href = url;

    }

</script>


</body>
</html>

templates/log.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Log</title>
</head>
<body>
    <h1>Log History!</h1>
    <h3>You are visiting from :</h3>
    <ul>
        <li>IP Address : {{ip}}</li>
        <li>Device: {{ device_type}}</li>
        <li>Browser: {{browser_type}} {{browser_version}}</li>
        <li>OS: {{os_type}} {{os_version}}</li>
    </ul>

    {%for log in logs %}

        <hr>
        <ul>
            <li>IP Address : {{log.ip}}</li>
            <li>Device: {{ log.device_type}}</li>
            <li>Browser: {{log.browser_type}} {{log.browser_version}}</li>
            <li>OS: {{log.os_type}} {{log.os_version}}</li>
            <li>address: {{log.location_country}} ({{log.location_city}})</li>
            <li>No: {{log.history.all|length}}
                {% with log.history.all|dictsortreversed:"date"|first as last_ap %}
                        (last: {{last_ap.date}})
                {% endwith %}
            </li>
        </ul>

    {%endfor%}

</body>
</html>

templates/tree.html
<li id="li-{{node.pk}}">
    <a href="javascript:void(0);" onclick="show_data(this)" id="{{node.pk}}">
        <div class="member-view-box">
                <div class="member-details">
                    <h1 style="font-size: 200%" id="branch-name-{{node.pk}}">{{node.name}}({{node.rank}})</h1>
                    <input type="hidden" id="name-{{node.pk}}" name="name" value="{{node.name}}">
                    <input type="hidden" id="fname-{{node.pk}}" name="fname" value="{{node.fname}}">
                    <input type="hidden" id="url-{{node.pk}}" name="url" value="{{node.url}}">
                </div>
        </div>
    </a>
    {% if node.person_set.all %}
        <ul id="branch-id-{{node.pk}}">
        {%for ch in node.person_set.all %}
            {%with node=ch template_name="tree.html" %}
                {%include template_name%}
            {%endwith%}
        {%endfor%}
        </ul>
    {% endif %}
</li>